import { Card, CardContent } from "../components/ui/card";
import { Link as LinkIcon, Copy, Calendar } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "./ui/button";
import { FRONTEND_URL } from "../services/apiService";

interface FormCardProps {
  formName: string;
  formLink: string;
  createdAt: string;
}

export function FormCard({ formName, formLink, createdAt }: FormCardProps) {
  const navigate = useNavigate();
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(
      `${FRONTEND_URL}/view/form/${formLink}`
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <Card className="h-full rounded-2xl shadow-xl border border-gray-200 bg-white transform transition-all duration-300 hover:scale-[1.02] hover:shadow-2xl group">
      <CardContent className="p-4 flex flex-col gap-4 h-full">
        <div className="flex items-start gap-4">
          {/* Decorative icon with gradient */}
          <div className="flex-shrink-0">
            <div className="h-12 w-12 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-500 flex items-center justify-center text-white shadow">
              <LinkIcon className="h-6 w-6" />
            </div>
          </div>

          <div className="flex-1 min-w-0">
            <div className="flex items-center justify-between gap-2">
              <p className="text-lg font-semibold text-gray-900 truncate">{formName}</p>
              {/* <span className="text-xs font-medium text-indigo-600 bg-indigo-50 border border-indigo-100 px-2 py-1 rounded">{formLink}</span> */}
            </div>

            <p className="text-sm text-gray-500 mt-2 line-clamp-2">A smart form generated by AI. Share the link with respondents and collect submissions quickly.</p>
          </div>
        </div>

        <div className="flex items-center justify-between text-sm text-gray-500">
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1">
              <Calendar className="h-4 w-4 text-gray-400" />
              <span>Created {new Date(createdAt).toLocaleDateString()}</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-2 py-1 rounded-md text-blue-600 bg-blue-50 hover:bg-blue-100 transition"
              title="Copy form link"
              aria-label="Copy form link"
            >
              <Copy className="h-4 w-4" />
              <span className="text-xs">{copied ? "Copied" : "Copy"}</span>
            </button>
          </div>
        </div>

        <div className="mt-auto">
          <Button
            onClick={() => navigate(`/view/form/${formLink}/submissions`)}
            className="w-full md:w-fit"
          >
            View Submissions
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
